### ISSUE TITLE
Not opening

### ISSUE THREAD

**Issue by Blackboard-24** [pashayogi/SETAN#10]
python2 SETAN.py
Traceback (most recent call last):
  File "SETAN.py", line 2, in <module>
    import os, sys, time, datetime, random, hashlib, re, threading, json, getpass, urllib, requests, mechanize
ImportError: No module named requests

**Comment by M1One** [comment]
this not tge only error there are 483 error only he or she forget the parentheses after print

**Comment by Mrrbadboy** [comment]
I have the same problems please someone help i need help

**Comment by Mrrbadboy** [comment]
> python2 SETAN.py
> Traceback (most recent call last):
> File "SETAN.py", line 2, in
> import os, sys, time, datetime, random, hashlib, re, threading, json, getpass, urllib, requests, mechanize
> ImportError: No module named requests
> 
> {Somebody help me please

I have same problem help please
