### ISSUE TITLE
Login Error

### ISSUE THREAD

**Issue by itsmysterious** [pashayogi/SETAN#2]
It worked well for some day but now whenever i try to login i get this error... Sometimes error also appears after successful login.

[●] Sedang Masuk COK ...
Traceback (most recent call last):
  File "SETAN.py", line 2128, in <module>
    login()
  File "SETAN.py", line 79, in login
    br.select_form(nr=0)
  File "/data/data/com.termux/files/usr/lib/python2.7/site-packages/mechanize/_mechanize.py", line 668, in select_form
    raise FormNotFoundError("no form matching " + description)
mechanize._mechanize.FormNotFoundError: no form matching nr 0
$

**Comment by kyawravi007** [comment]
Help me please bro....

**Comment by itsmysterious** [comment]
What kind of help?

**Comment by tayyabali785** [comment]
help

**Comment by omid0703458024** [comment]
Please help 
To copy comand to termux Thanks

**Comment by Lwinwai2018** [comment]
Login Error

**Comment by Blackboard-24** [comment]
When i try to open it shows like that please help me!
python2 SETAN.py
Traceback (most recent call last):
  File "SETAN.py", line 2, in <module>
    import os, sys, time, datetime, random, hashlib, re, threading, json, getpass, urllib, requests, mechanize
ImportError: No module named requests

**Comment by mohmad79** [comment]
Traceback (most recent call last):
  File "SETAN.py", line 2128, in <module>
    login()
  File "SETAN.py", line 102, in login
    menu()
  File "SETAN.py", line 157, in menu
    pilih()
  File "SETAN.py", line 170, in pilih                       menu_hack()
  File "SETAN.py", line 282, in menu_hack
    hack_pilih()
  File "SETAN.py", line 299, in hack_pilih
    super()
  File "SETAN.py", line 543, in super
    pilih_super()
  File "SETAN.py", line 579, in pilih_super
    for i in s['data']:
KeyError: 'data'

**Comment by bukshalishah** [comment]
Same issue

**Comment by zaqxsq** [comment]
اكو حل لهاي الاداة لو لا

**Comment by VolkovDz** [comment]
Try this:
 apt update && upgrade
 pkg install git
 git clone      https://github.com/pashayogi/SETAN
cd SETAN
pip install requests
pip2 install requests
python2 SETAN.py

**Comment by Nayeem21** [comment]
Traceback (most recent call last):
  File "SETAN.py", line 2, in <module>
    import os, sys, time, datetime, random, hashlib, re, threading, json, getpass, urllib, requests, mechanize
ImportError: No module named requests
.
..
.
when I run the code ..this show the error
Please help me to fix the error

**Comment by satra31** [comment]
same isuues

**Comment by Cyber2f08** [comment]
Why do you trust this, this just FAKE, cuz, facebook never make the API TO DO A HACK!


@pashayogi 
Lie

**Comment by pashayogi** [comment]
hai bro, SETAN NEW UPDATES

**Comment by forhadmnj** [comment]
Does anyone help me? how to hack Facebook Account by using pyhon

**Comment by bessam1234** [comment]
this problem its in evry tools like this tool , i think facbook make a new protect system
