### ISSUE TITLE
Mini Hack Facebook

### ISSUE THREAD

**Issue by Anon1331** [pashayogi/SETAN#5]

**Comment by Anon1331** [comment]
Can someone tell how to fix it?

**Comment by omid0703458024** [comment]
How to install this command bro??

**Comment by aungkaungpyae678** [comment]
Let’s go!

**Comment by aungkaungpyae678** [comment]
Traceback (most recent call last):
File "SETAN.py", line 2128, in 
login()
File "SETAN.py", line 63, in login
menu()
File "SETAN.py", line 157, in menu
pilih()
File "SETAN.py", line 170, in pilih
menu_hack()
File "SETAN.py", line 282, in menu_hack
hack_pilih()
File "SETAN.py", line 292, in hack_pilih
mini()
File "SETAN.py", line 384, in mini
data = urllib.urlopen('link here')
File "/usr/lib/python2.7/urllib.py", line 87, in urlopen
return opener.open(url)
File "/usr/lib/python2.7/urllib.py", line 185, in open
fullurl = unwrap(toBytes(fullurl))
File "/usr/lib/python2.7/urllib.py", line 1066, in toBytes
" contains non-ASCII characters")
UnicodeError: URL u'link here' contains non-ASCII characters

**Comment by Mrparca666** [comment]
Para el hack hay q poner el ID de la cuenta de Facebook?
